### ISSUE TITLE
pip not working to install this

### ISSUE THREAD

**Issue by lordjosephcosta** [jenca-adam/weather#1]
PIP or PIP3 do not work to install this. 

"Could not find a version that satisfies the requirement weather (from versions: )
No matching distribution found for weather"

Any ideas? Thank you!

**Comment by jenca-adam** [comment]
Oh, sorry , use pip install weather2.
I will manage to update the documentation

**Comment by jenca-adam** [comment]
Oh, sorry , use pip install weather2.
I will manage to update the documentation

so 28. 8. 2021 o 0:10 lordjosephcosta ***@***.***> napísal(a):

**Comment by jenca-adam** [comment]
There is an package on pypi called weather, but that is not the correct one, it's only documentation to another package
