### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by gabriel-fresan** [jenca-adam/weather#4]
hi i'm having an error at import.

whenever i try to import weather it gives me a error in "`selenium.webdriver`"  saying the following:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/g#####/.local/lib/python3.10/site-packages/weather/__init__.py", line 13, in <module>
>     from selenium.webdriver import *
> AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

i'm using linux and have the opera browser installed, does it have something to do with that ?

**Comment by jenca-adam** [comment]
I did not have that issue when i tested this, but it [apparently can happen with selenium](https://stackoverflow.com/questions/50113232/attributeerror-issue-module-selenium-webdriver-has-no-attribute-chrome). I will try to fix it in the next update
