### ISSUE TITLE
[ERROR] ModuleNotFoundError: No module named 'termios' when using on windows

### ISSUE THREAD

**Issue by unseeyou** [jenca-adam/weather#5]
termios is a library only available for UNIX systems, which windows is not.

**Comment by jenca-adam** [comment]
Weather does not import termios directly. It is possible that it is imported by another library. I will look at it and attempt to fix it soon.

**Comment by jenca-adam** [comment]
This is caused by getchlib (it is apparently not thoroughly tested), so I am  switching to getkey instead. I will update the package when I will manage to fix #4. #2 has obviously the same cause.

**Comment by unseeyou** [comment]
Cheers!
